### PR TITLE
WIP: Initial Dockerfile and supervisor configs

### PR DESCRIPTION
**Pull request by JayH5**

### CODE REVIEW

**Comment by JayH5** [comment]
```
[2016-04-11 13:29:07 +0000] [48] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/site-packages/gunicorn/util.py", line 357, in import_app
    __import__(module)
  File "/opt/graphite/webapp/graphite/wsgi.py", line 14, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python2.7/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    django.setup()
  File "/usr/local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/usr/local/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/local/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named tagging
```

**Comment by JayH5** [comment]
Seems to now want the database set up which is a good sign I guess.

I think the example WSGI application is not gonna work, though. I don't think the static file paths are correct.

**Comment by jerith** [comment]
> I think the example WSGI application is not gonna work, though. I don't think the static file paths are correct.

Can't we just use the paths it wants inside the container?

**Comment by jerith** [comment]
Also, there's no `local_settings.py` in here. :-)

**Comment by jerith** [comment]
Does the supervisor image this is based on give us a way to run a bootstrapping script? We need to create some paths and do database setup, etc.

**Comment by JayH5** [comment]
@jerith: You can just run custom commands, e.g.: `docker run --rm -it praekeltfoundation/graphite django-admin`

It's easier now that I've set `PYTHONPATH` and `DJANGO_SETTINGS_MODULE` in the Dockerfile.

**Comment by jerith** [comment]
You can't run custom commands like that through mesos, etc.

**Comment by JayH5** [comment]
Unfortunately not without fancy entrypoint scripts or something... but that's the same problem we have elsewhere.

**Comment by jerith** [comment]
An entrypoint script that allows this would probably be useful in our base images. It could just check for the existence of a `/bootstrap.sh` file or something and run that if present.

As it stands, this container will fail on startup without manual intervention. :-(

**Comment by jerith** [comment]
:+1: on everything prior to my commit. Should probably be tested on not-my-machine.

**Comment by jerith** [comment]
:+1:

**Pull request merged**
